# Basic Information
title: Adaptive Aggregation Networks for Class-Incremental Learning
authors:
  - Rakshith Subramanyam
  - Rakshith Subramanyam
affiliations:
  - name: Arizona State University
    link: https://www.mpi-inf.mpg.de/
  - name: Max Planck Institute for Informatics
    link: https://www.mpi-inf.mpg.de/
conference: 2021 IEEE/CVF Conference on Computer Vision and Pattern Recognition

# Search Engine Optimization (SEO)
keywords: minimal light
canonical: https://minimal-light-theme-mpi-inf.yliu.me/
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.

# Links
paper_link: ./assets/files/paper.pdf
slides_link: https://github.com/
poster_link: https://www.linkedin.com/
video_link: https://www.linkedin.com/
github_link: https://www.github.com/

# Images
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
enable_footnote: true

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
